mqtt:
  client:
    protocol: 4 # MQTTv311
  connection:
    host: localhost
    port: 1883
    keepalive: 60
  private_path: device/001
  serializer: json:dumps
  deserializer: json:loads
bridge:
  # ping pong
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:Bool
    topic_from: /ping
    topic_to: ping
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:Bool
    topic_from: ping
    topic_to: /pong
  # echo back
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /echo
    topic_to: echo
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: echo
    topic_to: /back
  # private path
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: std_msgs.msg:String
    topic_from: /private/echo
    topic_to: ~/echo
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: ~/echo
    topic_to: /private/back
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: vision_msgs.msg:Detection2DArray
    topic_from: /detectnet/detections
    topic_to: detectnetall
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: vision_msgs.msg:Detection2DArray
    topic_from: /detectnet/detections
    topic_to: detectnetContent
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: apriltag_ros.msg:AprilTagDetectionArray
    topic_from: /tag_detections
    topic_to: apriltagContent
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: apriltag_ros.msg:AprilTagDetectionArray
    topic_from: /tag_detections
    topic_to: apriltagall
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: std_msgs.msg:String
    topic_from: car
    topic_to: ""
  - factory: mqtt_bridge.bridge:RosToMqttBridge
    msg_type: apriltag_ros.msg:AprilTagDetectionArray
    topic_from: /tag_detections
    topic_to: apriltagSize